### ISSUE TITLE
Icon not show

### ISSUE THREAD

**Issue by happysurf** [aureliendavid/rsspreview#1]
Thank you for this extension very useful after the RSS feature dropping by Mozilla.
I need to copy rss link in address bar (or in the page preview) and paste it to my Netvibes pages.
I have installed rsspreview 1.1 but I don't see the icon in address bar,
This happen on Firefox 64 beta3.

(Suggestion) I don't know what your icon color but please consider the orange very good for all light and dark themes.

**Comment by aureliendavid** [comment]
Hi, 

This extension doesn't include the feed detection and address bar button features. 

For now the only thing it does is restore the preview page when visiting an rss feed url. 

I might add the feed detection later but my personal use is the preview page so that was my priority.

**Comment by aureliendavid** [comment]
In the meantime, this extension seem to handle the detection/button part: https://addons.mozilla.org/en-US/firefox/addon/erinome-rss-detector/

**Comment by IoApo** [comment]
Check also the https://github.com/nt1m/livemarks code here, especially the **/contentscripts** folder, as this adds a functionality to RSS-detection. Maybe there could be a chance for adding this detecting functionality? 

From a personal perspective, **RSS-discoverability** + **RSS-preview** would be just perfect, without any other bloated features/functionality. (so, then leaving the option to the user to continue as they want; if they need more RSS features, they can check other applications or services).
