### ISSUE TITLE
Feed detection not working on rlsbb.ru even though view source indicates rss feed

### ISSUE THREAD

**Issue by Riotous** [aureliendavid/rsspreview#16]
Yes, I realize rsspreview only has basic detection. This is a feature request. 

Go to http://rlsbb.ru/ with feed detection enabled. Note that there's no feed detection showing up.

The actual feed URL is http://rlsbb.ru/feed/ and view source gives specific mention to the feed. 
```
<link` rel="alternate" type="application/rss+xml" title="ReleaseBB" href="http://rlsbb.ru/feed/" />
	<link rel="alternate" type="application/atom+xml" title="ReleaseBB" href="http://rlsbb.ru/feed/atom/" />
<link rel="pingback" href="http://rlsbb.ru/xmlrpc.php" />
```

**Comment by Jimmy03** [comment]
Try choosing to have the xml file open in Firefox instead of downloading it.

**Comment by Riotous** [comment]
@Jimmy03 The feed preview shows up fine when I go to http://rlsbb.ru/feed/. If you miss a backslash at the end of that URL, it makes an xml download prompt show up, so I've amended my post.

The real issue is the lack of feed detection in sites that end in /feed/. Should be easy to implement, though. We want rsspreview to detect as many feeds automatically as possible without having the user have to guess the feed URL or click view source.

**Comment by aureliendavid** [comment]
you are absolutely right

should be fixed now

thanks for the report (please close the issue if confirmed fixed)

**Comment by Riotous** [comment]
Yep, it's fixed. Thank you for making such a great little addon. Will make new issues if I come across other sites that don't get detected.
