### ISSUE TITLE
Feed detection doesn't work on this site…

### ISSUE THREAD

**Issue by sojusnik** [aureliendavid/rsspreview#18]
… https://www.nachdenkseiten.de

Although the page source contains https://www.nachdenkseiten.de/?feed=rss2.

**Comment by aureliendavid** [comment]
see point 2 here: https://github.com/aureliendavid/rsspreview/issues/11#issuecomment-455796739

there's a proper way to declare an rss feed in a page, I can't detect just detect any link to any potential feed url
