### ISSUE TITLE
Site with feed ending in /feed/ not detected with 3.0.1 (grubgrade.com)

### ISSUE THREAD

**Issue by Riotous** [aureliendavid/rsspreview#19]
This is on Firefox 64.0.2 with rsspreview 3.0.1

Here's another site with an undetectable feed to add to rsspreview's capabilities.

- Go to https://www.grubgrade.com/

- See that the feed is not detected despite it being https://www.grubgrade.com/feed/

Relevant mentions in view source: 

`href="/feed/" title="RSS Feed">Subscribe</a></div><div
href="https://www.grubgrade.com/feed/">Entries <abbr
title="Really Simple Syndication">RSS</abbr></a></li><li><a
href="https://www.grubgrade.com/comments/feed/">Comments <abbr
title="Really Simple Syndication">RSS</abbr></a></li><li><a`

I went through every site I've visited in the past 30 days by hand today to check feed detection for each site and this is the only one that didn't get detected by 3.0.1, so fixing this will probably take care of most, if not all sites.

**Comment by aureliendavid** [comment]
Hi, 

I don't think we want to support this. 

Although it looks obvious to a human that this is an rss link, it's still just a generic link on the page (`<a href=".."`). If we start trying to detect rss feeds among all the links on a page it opens an infinite number of possible variations and particular cases to take into account. 

That's the reason why there is a specific way to declare an rss feed in a page, using the `<link rel="alternate" ...` syntax, which is predictable. 

So I'm probably going to stick to these and not over-complicate things. 

(also if the feed is in a regular page link, chances are it's visible and you can just click that)
