### ISSUE TITLE
Atom feeds without rel="alternate" attributes displayed incorrectly

### ISSUE THREAD

**Issue by apropostech** [aureliendavid/rsspreview#2]
Atom feeds without rel="alternate" attributes are displayed incorrectly as text only without link to "href" attribute. According to the [standard](https://validator.w3.org/feed/docs/atom.html) the only required attribute for <link> elements is "href".

**Comment by aureliendavid** [comment]
yeah I didn't have many examples for atom feeds so there was some guesswork involved

do you have a sample feed for the case you describe? 

thanks for the report

**Comment by aureliendavid** [comment]
fixed by https://github.com/aureliendavid/rsspreview/commit/0f3e9fa3f831f60fd57158d51a756091d4c4f7ad

thx
