### ISSUE TITLE
Could not you use the activeTab permission?

### ISSUE THREAD

**Issue by rugk** [aureliendavid/rsspreview#22]
I doubt you really need permission for `<all urls>`, i.e. all sites, should not [activeTab](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activeTab_permission) work, too?

IMHO it's good to reduce the permissions.

**Comment by rugk** [comment]
Okay, so closing?

**Comment by aureliendavid** [comment]
I guess yeah, thanks for the suggestion though
