### ISSUE TITLE
Inoreader compiled feeds don't display component feeds

### ISSUE THREAD

**Issue by lcenvs** [aureliendavid/rsspreview#24]
I am using Inoreader to compile/export feeds consisting of a number of valid component feeds. The Inoreader feed (e.g., [this one](https://www.inoreader.com/stream/user/1006272833/tag/ENVSRSSFeedsFa18)) works fine in other contexts, but not via RSS Preview, which displays only the feed title.

The first few lines of the compiled feed are below, which may help me understand why this issue...thanks...Jim P.

`<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
<channel>
<title>ENVSRSSFeedsFa18 via jproctor on Inoreader</title>
<link>
https://www.inoreader.com/stream/user/1006272833/tag/ENVSRSSFeedsFa18/view/html
</link>
<description>
<![CDATA[ ]]>
</description>
<atom:link href="https://www.inoreader.com/stream/user/1006272833/tag/ENVSRSSFeedsFa18" rel="self" type="application/rss+xml"/>
<generator>Inoreader (https://www.inoreader.com)</generator>
<pubDate>Tue, 05 Feb 2019 23:11:53 +0000</pubDate>
<lastBuildDate>Tue, 05 Feb 2019 23:11:53 +0000</lastBuildDate>
<language>en-US</language>
`

**Comment by aureliendavid** [comment]
the feed at https://www.inoreader.com/stream/user/1006272833/tag/ENVSRSSFeedsFa18 is displaying properly for me with rsspreview 

is it not the case for you ? what version of firefox and rsspreview are you using ?

**Comment by lcenvs** [comment]
yes, you are correct; this is now working for me just fine, thanks...Jim P.
