### ISSUE TITLE
Code overflow

### ISSUE THREAD

**Issue by AlfredoRamos** [aureliendavid/rsspreview#25]
Hi,

First off, thanks for this add-on, I find it very useful.

I've been using this for a couple of days and found that feeds that have `<code>` tags on it, overflows it content.

![20190208_155052](https://user-images.githubusercontent.com/4165935/52508300-c379e300-2bb9-11e9-8f06-10a5fb01a599.png)

**Comment by aureliendavid** [comment]
Hi, thanks for the report and the PR. 

I think wrapping pres with 

```
pre {
  white-space: pre-wrap;
}
```

is enough. 

Can you test with v3.3 if it works in your case? If it doesn't do you have a link to a feed where the problem persists?

Thanks

**Comment by AlfredoRamos** [comment]
Not really, that just break long lines into new ones breaking the formatting of the code. The changes I proposed add scrolls which in my opinion is a better approach.

I'll look for alternatives, thanks anyways.

**Comment by aureliendavid** [comment]
you're right, I didn't catch what you wanted to do, I just saw the long debug line in your screenshot and thought you wanted to word-wrap pres

if you reopen your PR I can merge it (otherwise i'll just add the changes by hand)

thanks

**Comment by aureliendavid** [comment]
> if you reopen your PR I can merge it (otherwise i'll just add the changes by hand)

no need, I had it checked out so I could merge it

v3.3.1 should behave as you wanted @AlfredoRamos
