### ISSUE TITLE
Conflict with uMatrix extension

### ISSUE THREAD

**Issue by SlashTray** [aureliendavid/rsspreview#27]
Test case: http://radiofrance-podcast.net/podcast09/rss_10217.xml

Despite of uMatrix not detecting anything on that XML page, it has to be "powered off" (via the uMatrix On/Off button, for domain radiofrance-podcast.net) in order to be able to download MP3 podcasts normally.

Otherwise an error message displays (here translated from French), preventing the MP3 file download:

"Download error"
The download can't be saved since an unknown error occurred.
Please try again.

Original French error message:

"Erreur de téléchargement"
Le téléchargement ne peut pas être enregistré car une erreur inconnue est survenue.
Veuillez essayer à nouveau.

**Comment by aureliendavid** [comment]
hi, 

thanks for the report and finding the incompatible extension

I'll try to find what's going on between rsspreview and umatrix

**Comment by SlashTray** [comment]
Hi Aurélien,

no need for additional investigations, I've just identified the issue and worked around it :)

Nothing to do with RSSPreview (sorry for my bad assumption), the "problem" comes from uMatrix standard configuration, which blocks any media not belonging to the visited domain (radiofrance-podcast.net in my case).

Podcasts are actually hosted on rf.proxycast.org, as I could read on the uMatrix logger-ui.html page (accessible via uMatrix "Aller au Journal" top-right option). Allowing media coming from domain rf.proxycast.org solved the issue.

I guess you can now close this RSSPreview (false) issue ;)

Thanks again for your extension, it does exactly the job I was expecting, don't change anything!

**Comment by aureliendavid** [comment]
ok cool then :)

thanks for the diagnosis
