### ISSUE TITLE
Add an option for custom CSS

### ISSUE THREAD

**Issue by personalmountains** [aureliendavid/rsspreview#28]
Add an option for arbitrary CSS to be injected in the pages so users can customize the appearance of the previews.

At worse, give a very specific `id` to the `<body>` of previews so it can be detected in `userContent.css`.

**Comment by aureliendavid** [comment]
Hi, 

I did both in v3.4

The `<body>` element will now have id `rsspreviewBody`. 

I haven't tested the custom css option too much but it should work.

**Comment by personalmountains** [comment]
The option works great, thanks!
