### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by jonafato** [aureliendavid/rsspreview#31]
Is rsspreview open source? If so, can you add license information to the project? If you don't know what license to choose, GitHub's https://choosealicense.com/ is a great guide to finding the right one for you.

**Comment by aureliendavid** [comment]
yeah, I had checked the MPL2.0 on AMO by default without thinking about it, but not on github

to be honest I could never grasp the subtle differences between the myriad licenses out there, so I'm usually tempted to use the WTFPL

I've added the MIT license here and on AMO now, it seems pretty permissive and straightforward
