### ISSUE TITLE
[feature] feed URL building for unsupported sites

### ISSUE THREAD

**Issue by atomGit** [aureliendavid/rsspreview#34]
i think it's very handy to be able to access feeds for sites like YouTube, BitChute, Vimeo, etc. - while all of these sites will generate the XML, none of them advertise the feed URL, however they are easily built by simply editing the URL of the user channel and this can be done using simple RegEx (no feed detection is necessary)

please see: [How to access RSS feeds for websites that don’t advertise one](https://12bytes.org/articles/tech/how-to-access-rss-feeds)

**Comment by Draky50110** [comment]
Better : use RSS-Bridge : https://github.com/RSS-Bridge/rss-bridge/

**Comment by atomGit** [comment]
i'd like to ask that this issue be reconsidered

RSSPreview is already generating feed links for YouTube and so i don't expect it would be difficult to do the same for other popular platforms, such as BitChute and Vimeo...

`https://www.bitchute.com/feeds/rss/channel/<CHANNEL ID>`
`https://vimeo.com/<CHANNEL ID>/videos/rss`

**Comment by aureliendavid** [comment]
It already works for vimeo channels for me. 

I don't want to have anything to do with that other website.
