### ISSUE TITLE
Doesn't detect some feeds

### ISSUE THREAD

**Issue by l0b0** [aureliendavid/rsspreview#38]
It does not seem to detect the feed on idlewords.com.

**Comment by aureliendavid** [comment]
hm it works for me, what version/browser are you using?

did you enable feed detection in the addon options?

**Comment by l0b0** [comment]
Firefox 67.0. I didn't change any of the defaults.

**Comment by aureliendavid** [comment]
feed detection needs to be enabled explicitly in the options for it to work

I agree that it should be on by default (I'll do that) but originally the addon only did the preview page and detection was added later as an optional feature, but by now most people use the detection too so it would make sense to enable it by default

**Comment by aureliendavid** [comment]
i'm closing the issue, please reopen if needed, thanks
