### ISSUE TITLE
Blogspot titles link to the comments instead

### ISSUE THREAD

**Issue by Onurtag** [aureliendavid/rsspreview#40]
Most other addons link to the blog post correctly.
A random blogspot example: https://1bestcsharp.blogspot.com/feeds/posts/default?start-index=1&max-results=2
I can give more examples if you need them.

Thanks for the great work on the addon.

**Comment by aureliendavid** [comment]
hi, 

thanks for the report

you're right, the addon picked up the wrong link

should be fixed in v3.9

if you confirm it fixed you can close the issue

thanks

**Comment by Onurtag** [comment]
Thank you. Its all good now.
