### ISSUE TITLE
support for atom:name

### ISSUE THREAD

**Issue by ruv** [aureliendavid/rsspreview#41]
Could you please add support for `atom:name` to show an entry author name in the preview? (see in [rfc4287](https://tools.ietf.org/html/rfc4287#section-3.2.1) for reference).

An atom-feed example: a [feed for firefox-dev](https://groups.google.com/forum/feed/firefox-dev/msgs/atom.xml?num=15) group.

**Comment by aureliendavid** [comment]
Hi, 

I've added it as an option in v3.10. 

It's disabled by default because I'm not sure that many people will use it so you'll have to go enable it in the addon options. 

If the style doesn't suit you, you can enable custom css in the options and change the `author` class.
