### ISSUE TITLE
BlogTalkRadio feeds don't show correctly

### ISSUE THREAD

**Issue by Jimmy03** [aureliendavid/rsspreview#42]
I just see a grey background with a wall of xml text

example:
http://www.blogtalkradio.com/lifetransformationradio/podcast

**Comment by aureliendavid** [comment]
the server serves it as `text/plain` so firefox doesn't recognize the url as being an xml file and in turn the addon doesn't detect it as a feed

the server needs to return one of these `Content-Type`s:
- `application/rss+xml`
- `application/xml`
- `text/xml`

it won't work otherwise

**Comment by Jimmy03** [comment]
I seem to remember BlogtalkRadio feeds working in Firefox when it still had rss support

**Comment by aureliendavid** [comment]
I keep old firefox versions with rss support to check the differences with the addon, I can confirm that it doesn't work on older firefox either:

![btr](https://user-images.githubusercontent.com/7168263/62823484-7b9c3e80-bb91-11e9-9f38-3207c1378d6e.png)

(same with firefox 46)

perhaps something changed on the server side?
