### ISSUE TITLE
Addon doesn't show author if stated as <dc:creator>

### ISSUE THREAD

**Issue by CennoxX** [aureliendavid/rsspreview#43]
An author can be named in the author tag (only valid if with e-mail adress) or in the tag `<dc:creator>` (where no e-mail has to be stated). The addon currently only shows the author if the author-tag is used. It should display the author also if it is only stated in `<dc:creator>`.

See http://www.rssboard.org/rss-profile#namespace-elements-dublin-creator

**Comment by aureliendavid** [comment]
thanks, I didn't know about this one

I pushed a v3.10.1 to add it, please check if it's ok for you
