### ISSUE TITLE
content:encoded field is ignored

### ISSUE THREAD

**Issue by grr** [aureliendavid/rsspreview#45]
If the option "Display full articles even when summaries are present" is enabled, the 
description field is used even if the content:encoded field is also present.
* Example feed: https://rlsbb.ru/category/tv-shows/feed/
* Reference: https://stackoverflow.com/questions/7220670/difference-between-description-and-contentencoded-tags-in-rss2

**Comment by aureliendavid** [comment]
`content:encoded` should now be supported in v3.11

if the "display full articles.." option is checked, `content:encoded` will take precedence over `description`

thanks for the report, reopen the issue if the problem persists
