### ISSUE TITLE
Use browser language for language-dependent content

### ISSUE THREAD

**Issue by jtotht** [aureliendavid/rsspreview#47]
Currently [`getlang()`](https://github.com/aureliendavid/rsspreview/blob/90bce18337f63c4cdcf4404d2d6cc39b35c2405b/rsspreview.js#L58) returns the user’s desired page language used on websites. I think it should rather use the language of the browser itself (as it’s more part of the browser UI), i.e., `getlang`’s body should be changed to
```js
return browser.i18n.getUILanguage();
```
(or maybe simply substituted everywhere). [Documentation on MDN.](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getUILanguage)

**Comment by aureliendavid** [comment]
thanks for the info, it makes sense to me

i'll include it in the next release

**Comment by jonafato** [comment]
@aureliendavid looks like this is in `master` and just waiting on a release? Should this issue be closed?

**Comment by aureliendavid** [comment]
yeah I was waiting to have other stuff to include to upload a release on AMO but I kinda forgot about it

let's keep the issue open to remind me to do it. I can't right now but I should have some time tomorrow

**Comment by aureliendavid** [comment]
this is now included in release v3.12.1
