### ISSUE TITLE
Does rsspreview work in Firefox 64 beta?

### ISSUE THREAD

**Issue by oneofthedamons** [aureliendavid/rsspreview#5]
There's no indication of an available feed for either https://fastmail.blog/ or https://blog.mozilla.org/futurereleases/

What am I supposed to see?

**Comment by aureliendavid** [comment]
it doesn't do feed detection, it just recreates the preview page when you visit a feed url

try https://fastmail.blog/rss/ or https://blog.mozilla.org/futurereleases/feed/
