### ISSUE TITLE
Campaign for built-in RSS Preview in browsers

### ISSUE THREAD

**Issue by sjehuda** [aureliendavid/rsspreview#50]
I think this feature is a must in any web browser.
Have a look at my [demo project](https://github.com/OtterBrowser/otter-browser/issues/1272), which works with any browser that does not interrupt XSLT.

**Comment by jonafato** [comment]
@sjehuda Firefox [used to have RSS preview support](https://support.mozilla.org/en-US/kb/feed-reader-replacements-firefox), but it was removed in 2018 for maintainability reasons. rsspreview recreates that support and is one of many such extensions included in Firefox's curated list of Feed Readers. I would be surprised if Firefox reintroduced built-in support so soon after removing it but would welcome the change, but I'm not sure how it relates to this project; is there something actionable to do here?

Side note: I was unable to get your linked demo to work in Firefox or Chrome.

**Comment by sjehuda** [comment]
I know that story.  There is also [this article](http://camendesign.com/blog/rss_is_dying).

> Side note: I was unable to get your linked demo to work in Firefox or Chrome.

Me too. Try to open it using Falkon or Otter Browser.  You should see [this screenshot](https://cloud.githubusercontent.com/assets/19249089/20603865/29eb6344-b26c-11e6-9b9b-f062f635205a.png) (1MB).

I think we need to expand this extension into a campaign project.

Ping @reeywhaar

**Comment by jonafato** [comment]
>Me too. Try to open it using Falkon or Otter Browser. You should see this screenshot (1MB).

More detail: in Firefox, the link prompts me to download a file (I'm guessing that's Firefox's default handling of the content type or something). Chrome and Falkon both have the same behavior of rendering the feed as plaintext XML for me, which is actually less useful than the rich XML display the browser provides by default.

>I think we need to expand this extension into a campaign project.

I'm not a maintainer of this project, but I've contributed a couple of features and watch it for updates. If there was a larger campaign to broadly improve RSS, I'd certainly follow along and participate where possible. Does something like this exist already?

**Comment by sjehuda** [comment]
On Tue, 07 Apr 2020 15:12:38 -0700
Jon Banafato <notifications@github.com> wrote:

> >I think we need to expand this extension into a campaign project.
> 
> I'm not a maintainer of this project, but I've contributed a couple of features and watch it for updates. If there was a larger campaign to broadly improve RSS, I'd certainly follow along and participate where possible. Does something like this exist already?
> 

I think not.  I'd love to begin ASAP.

**Comment by jonafato** [comment]
IMHO this seems like a discussion beyond the scope of a GitHub issue on a single RSS-related browser extension. If you plan to put together a larger discussion regarding what a campaign like that would entail and / or how RSS tooling cam be improved for end-users, I'd be interested in following along.

**Comment by aureliendavid** [comment]
I agree. I'm all for more support of rss in browsers and if a project wants to integrate this extension I'll be happy to help. But I don't think this is right place to discuss it. 

Thanks for the support though.

**Comment by sjehuda** [comment]
guys please ping me an email sjehuda@yandex.com (this message will be deleted from web)
