### ISSUE TITLE
Does not work with the following feed

### ISSUE THREAD

**Issue by sojusnik** [aureliendavid/rsspreview#52]
In [this](https://blog.railcargo.com/de/newsfeed) feed the text is present, but the preview has no layout.

Happens with v3.12.1 on Firefox 75.

**Comment by aureliendavid** [comment]
the reason is that the server serves this page wih:

```
Content-Type: text/html;
```

For it to be treated as an rss feed the `Content-Type` should be `application/rss+xml` or at least `text/xml` otherwise firefox will interpret it as html and display this block of text before the extension can process it.

**Comment by sojusnik** [comment]
Thanks for the clarification!
