### ISSUE TITLE
Does Not Load When Using Back Button / Cached Pages

### ISSUE THREAD

**Issue by TheDocTrier** [aureliendavid/rsspreview#53]
If you visit a site (eg [mine](https://disjointunion.link/)), the RSS preview icon appears correctly.
If you navigate to the Archive, the RSS preview icon appears correctly.
If you then use the back and forward buttons (causing Firefox to load cached copies of the pages) no RSS preview icon will appear.
Using the debugger, it seems that the `rsspreview.js` IIFE is not invoked when the cached version is loaded.

**Comment by aureliendavid** [comment]
hi, 

thanks for the report and sorry for the late answer

unfortunately, this is how firefox works and I don't think I have a way around it, when you press the back button the extension code is not run again and the feeds are not detected, you need to f5 at this point
