### ISSUE TITLE
No longer works in TOR

### ISSUE THREAD

**Issue by Ha1zGw** [aureliendavid/rsspreview#56]
Since the last update the addon has stopped working in TOR Browser (tested on w10 and flatpak), the icon in the address bar has disappeared and the preview page is broken.

Any hope that it's going to be fixed? Thanks for reading.

**Comment by aureliendavid** [comment]
Thanks for the report, I hadn't realize we couldn't use regexp named groups on older firefox versions. 

Should be fixed in v3.13.1
