### ISSUE TITLE
strange code on top / bottom of RSS feeds

### ISSUE THREAD

**Issue by lmjst** [aureliendavid/rsspreview#61]
Since a few weeks the following code is displayed at the bottom (sometimes on top) of the feeds :
`try { Object.defineProperty(screen, "availTop", { value: 0 }); } catch (e) {} try { Object.defineProperty(screen, "availLeft", { value: 0 }); } catch (e) {} try { Object.defineProperty(screen, "availWidth", { value: 1600 }); } catch (e) {} try { Object.defineProperty(screen, "availHeight", { value: 900 }); } catch (e) {} try { Object.defineProperty(screen, "colorDepth", { value: 24 }); } catch (e) {} try { Object.defineProperty(screen, "pixelDepth", { value: 24 }); } catc` .....

This is displayed independently from the feed source / CMS 
I thought it was my browser but testing another feed display plugin doesn't give the error (but I prefer yours since it loads faster)

thanks
dd

**Comment by aureliendavid** [comment]
I have not seen that happening anywhere. 

Do you have an example feed where it happens? What OS and firefox version are you using?

This bit of code is not a part of rsspreview, it seems to return some hits on google but I don't see where it comes from.

**Comment by aureliendavid** [comment]
closing this because no updates

reopen if necessary
