### ISSUE TITLE
RSS Feeds Opening New Tab

### ISSUE THREAD

**Issue by supersaiyandoyle** [aureliendavid/rsspreview#62]
Is there an option or custom CSS to prevent the opening of a new tab when clicking on an item in an RSS feed? I just want it to open in the same tab the feed is, I'm always having to either drag the link to the address bar or open a new tab and close the RSS tab, it gets annoying.

**Comment by aureliendavid** [comment]
Hi, 

it's a good suggestion, I added an option to control this in v3.15

after updating, look for the `Open feed in new tab` checkbox on the options page

cheers
