### ISSUE TITLE
I can't set .rss file type to Open in Firefox

### ISSUE THREAD

**Issue by Jimmy03** [aureliendavid/rsspreview#63]
Is this addon dependent on being able to set .rss files to "Open in Firefox" under the Applications section in Firefox Options? Now it won't let me set it to "Open in Firefox", instead it just saves the .rss file as a download.

Some rss feeds are actually in the format of **website/feed.rss** and Firefox treats it as a file, and not a viewable feed

Firefox>Options>General>Applications

.rss files

Edit: A workaround seems to be to set .rss to "Always Ask" in the Firefox Applications setting, and then when prompted by Firefox what to do with it, select Open with Firefox. The problem with this is that you have to do it every time, and it also will download the .rss file to Username\AppData\local\Temp which I don't really want, as it's potentially insecure. I guess in order for Firefox to open the .rss file it needs to download it locally, and then the Addon shows the feed preview.

**Comment by jonafato** [comment]
Do you have an example of a feed with this behavior? This extension uses the [content type header](https://github.com/aureliendavid/rsspreview/blob/8a6ccab606b2a03eb0ea08d192fc30a6c6cd95da/background.js#L12) to decide what to display, so if a feed isn't being rendered by the extension when you expect it to, it may be a problem in how the server is returning the content.

**Comment by Jimmy03** [comment]
> 
> 
> Do you have an example of a feed with this behavior? This extension uses the [content type header](https://github.com/aureliendavid/rsspreview/blob/8a6ccab606b2a03eb0ea08d192fc30a6c6cd95da/background.js#L12) to decide what to display, so if a feed isn't being rendered by the extension when you expect it to, it may be a problem in how the server is returning the content.

@jonafato 
This one does it: https://www.veritasradio.com/vs.rss

**Comment by aureliendavid** [comment]
Hi, 

The file extension doesn't matter, as @jonafato said the extension looks at the content-type header to see if it's an rss feed. 

Your first example sends `application/x-rss+xml` which is meaningless, the correct content type for rss feeds is `application/rss+xml`. (the second example is correct so it works)

(and adding exceptions for each invalid feed would be a pain so it's up to the site to fix its feed)

**Comment by Jimmy03** [comment]
@aureliendavid 
I think I see what you are saying,

Somehow Podbay is able to read and render that feed correctly on their site:  
https://podbay.fm/p/veritas-w-mel-fabregas-or-non-member-feed-or-subscribe-at-veritasradiocom-to-listen-to-all-parts  
  
Not sure what methods they used to get it to work
