### ISSUE TITLE
RSS feed from WordPress

### ISSUE THREAD

**Issue by geo711** [aureliendavid/rsspreview#65]
I frequent the Pyramydair.com airgun blog. The blog uses WordPress and when I request comments using the RSS comments feed, I am only able to view the most recent twenty comments. In the past I was able to view over 100 comments from the feed. Is this a restriction coming from WordPress, or has something changed in rsspreview. I have used your extention in Firefox since they stopped supporting an RSS reader. Thank you.

**Comment by aureliendavid** [comment]
Hi, 

The restriction doesn't come from rsspreview so it has to come from the site. You can check the feed source code to see that rsspreview displays all this is being sent.
