### ISSUE TITLE
Relative time option please

### ISSUE THREAD

**Issue by bztsrc** [aureliendavid/rsspreview#67]
Hi!

Let me first start with how much I like your add-on! I've checked MANY, but they are usually very bloated, full of features that I don't need. Yours does exactly what's needed, no bloat! Good job! I only have two minor issues with it to be perfect:

Please add a checkbox on the preferences page to allow relative times, like "1 minute ago", "2 weeks ago" etc.
[This](https://addons.mozilla.org/en-US/firefox/addon/want-my-rss/) add-on can do that with RSS feeds (but not with Atom feeds for some reason). It is Open Source, you might want to learn from its [source](https://github.com/Reeywhaar/want-my-rss/blob/master/ts/relativeDate.ts) how to do it, but seems pretty simple.

Thanks!

Another issue, with RSS there are no links on the title for some reason. The urls are in the source with a "guid" tag. [For example](https://freegamedev.net/rss). I believe this should be a simple fix too, but not as important as the relative times (the sites I'm interested in provide both RSS and Atom feeds).

If you need any help with the coding (you don't have time etc.), let me know and I'll post a PR for these.

Cheers,
bzt

**Comment by aureliendavid** [comment]
Hi, 

thanks for the report and sorry for the late reply

> 
> Please add a checkbox on the preferences page to allow relative times, like "1 minute ago", "2 weeks ago" etc. [This](https://addons.mozilla.org/en-US/firefox/addon/want-my-rss/) add-on can do that with RSS feeds (but not with Atom feeds for some reason). It is Open Source, you might want to learn from its [source](https://github.com/Reeywhaar/want-my-rss/blob/master/ts/relativeDate.ts) how to do it, but seems pretty simple.


I don't really like relative time and I try to keep the code as simple as possible so I probably won't add this

feel free to submit a PR with this option if you really want it though


> Another issue, with RSS there are no links on the title for some reason. The urls are in the source with a "guid" tag. [For example](https://freegamedev.net/rss). I believe this should be a simple fix too, but not as important as the relative times (the sites I'm interested in provide both RSS and Atom feeds).
> 

I do see links on titles now, maybe the feed have changed since the issue has been posted

please reopen if needed
