### ISSUE TITLE
Links within links show HTML markup

### ISSUE THREAD

**Issue by matthewkogan** [aureliendavid/rsspreview#7]
The attached RSS XML, which has come from JIRA 7.5.0, is showing HTML markup in the link, which Firefox 63 does not.
[RSS test.txt](https://github.com/aureliendavid/rsspreview/files/2671722/RSS.test.txt)

**Comment by aureliendavid** [comment]
hi, 

this should be fixed in v2.2

thanks for the report, reopen the issue if needed
