### ISSUE TITLE
Restyle for increased productivity

### ISSUE THREAD

**Issue by GreenLunar** [aureliendavid/rsspreview#71]
Suggested style with a search filter ![2017-09-22-164717-rss](https://user-images.githubusercontent.com/6865273/30747609-76896290-9fb6-11e7-85e2-f1b14d44c65b.png)

**Comment by aureliendavid** [comment]
Hi, thanks for the suggestion 

I want to keep the display page as simple as possible and not add stuff like a search filed 

the current css is based on how firefox used to display feeds when it supported it

you can add custom css in the option to get it to look closer to your liking

**Comment by GreenLunar** [comment]
On Sat, 27 May 2023 04:18:01 -0700
"A. David" ***@***.***> wrote:

> Hi, thanks for the suggestion
>
> I want to keep the display page as simple as possible and not add
> stuff like a search filed
>
> the current css is based on how firefox used to display feeds when it
> supported it
>
> you can add custom css in the option to get it to look closer to your
> liking
>

Please look into my userscript and see what you can copy from it.

https://greasyfork.org/en/scripts/465932-newspaper-native-rss-reader

Please see instructions
https://openuserjs.org/scripts/sjehuda/Newspaper#gecko

**Comment by GreenLunar** [comment]
Oh, now I see.

This was an idea from an Otter post.

I've decided to add a **table of contents**.

If you are using XSLT to render XML into HTML, please look into this
userscript.

https://openuserjs.org/scripts/sjehuda/Newspaper_(XMLHttpRequest)/source#H0a335328289b6d5f6f0c5022ae4dd66947253eef8c8935e32a1ce54260f0694bbd7b8d5f186d7628fe4e7f08e4853804ed0d27d7be427c55d1b248323bd28cb0L201

FYI, the new version of my userscript use DOMParser instead of
XSLTProcessor because Mozilla sabotaged it.

https://openuserjs.org/garage/Why_my_script_doesnt_work_with_Firefox#comment-18732ed911e
