### ISSUE TITLE
Preview does not work on feeds that contain XSL stylesheets

### ISSUE THREAD

**Issue by afontenot** [aureliendavid/rsspreview#72]
Or at least, it doesn't work on this one, and that seems like the plausible reason: https://feeds.bbci.co.uk/news/rss.xml

I see the feed as styled by Firefox instead of the preview created by the extension.

All [other](https://feeds.npr.org/1001/rss.xml) feeds continue to work fine.

**Comment by aureliendavid** [comment]
hi, 

this is intended, when a feed has a stylesheet firefox converts it to html before extensions can do anything with it, so we cannot recognize it as a feed to be displayed, so the stylesheet display is kept
