### ISSUE TITLE
XML Parsing Error: reference to invalid character number

### ISSUE THREAD

**Issue by kumarv1978** [aureliendavid/rsspreview#73]
Sometimes when invalid character is detected in the feed, entire preview is not coming. Is it possible to exclude the particular feed entry & show the remaining entries in the preview?

XML Parsing Error: reference to invalid character number
Location: https://www.dailythanthi.com/feed
Line Number 5864, Column 36:

When I checked the actual xml, the character is &#29.

**Comment by aureliendavid** [comment]
hi,

unfortunately this is firefox throwing this error even before the extension had a chance to run so there's not much we can do, except encouraging the website to send a valid xml feed
