### ISSUE TITLE
Show feeds for Blogger labels

### ISSUE THREAD

**Issue by anewuser** [aureliendavid/rsspreview#74]
When you view a Blogger label (category), the extension button could include label-specific feeds:

* https://blogging.nitecruzr.net/search/label/Blogger → `https://blogging.nitecruzr.net/feeds/posts/default/-/Blogger/?alt=rss`
* https://chromereleases.googleblog.com/search/label/Chrome%20for%20Android → `https://chromereleases.googleblog.com/feeds/posts/default/-/Chrome%20for%20Android/?alt=rss`

**Comment by aureliendavid** [comment]
hi, 

thanks for the report

unfortunately we only detect the feeds that are advertised in the source, in this case it's only the general feed of the blog

I don't want to add a specific rule for this site to guess the url of the label feed, which could change at any point 

maybe you could ask the blogger team to add the label feed in the source on these pages

**Comment by anewuser** [comment]
@aureliendavid Blogger is a blogging service provided by Google. It has used the same URL structure for feeds for many years.
