### ISSUE TITLE
YouTube feed detection stopped working

### ISSUE THREAD

**Issue by sojusnik** [aureliendavid/rsspreview#75]
Seems that YouTube made some recent changes. Could you have a look please?

**Comment by jonafato** [comment]
It seems like this is only due to new "handle" URLs being used in YouTube's UI. I've just opened a PR that should solve this issue. If there are other issues with YouTube feed detection, please provide example YouTube links that the extension fails to identify feeds for.

**Comment by aureliendavid** [comment]
thanks for both reporting the issue and providing the fix! 

this is now available in version 3.19 on amo
