### ISSUE TITLE
Some encoded characters do not display properly

### ISSUE THREAD

**Issue by mmkthecoolest** [aureliendavid/rsspreview#80]
I found a [feed from APA.org](https://www.apa.org/news/psycport/psycport-rss.xml) that uses some encoded characters for apostrophes. In both my RSS readers (Newsflow for Windows 10 and Feeder for Android), the apostrophe is displayed properly. However in RSSPreview, they remain displayed as `&apos;`. According to [this stackoverflow page](https://stackoverflow.com/a/18551371/10219333), this was added to the HTML5 standard (I don't know if this is relevant, since I understand that this is based off Firefox's removed RSS preview feature).

I am not sure if a similar issue has been reported before, as I was unable to find something similar from the closed or opened issues lists. I apologize in advance if it has been reported.

**Comment by aureliendavid** [comment]
Hi, 

Thanks for reporting. 

This should now be fixed in v3.21.

**Comment by mmkthecoolest** [comment]
Yep. Looks like it works properly now. Feel free to close.
