### ISSUE TITLE
GitHub feeds inconsistent tags and release feeds

### ISSUE THREAD

**Issue by Jon-guy30** [aureliendavid/rsspreview#82]
Just a heads up, not really a problem per se, when accessing GitHub feeds for software/program and project updates the feed icon doesn't first show up. Only after going to the releases page does it appear, but only after a refresh, but when you go to tags and refresh again the feed icon disappears until you go back to releases, refresh again and then go to tags without refreshing in tags THEN it works again. Really strange behavior.

So...
1. Go to any project page e.g. https://github.com/bleachbit/bleachbit/tags notice the feed isn't there
2. Then go to https://github.com/bleachbit/bleachbit/releases, notice the feed still isn't there.
3. When in releases, hit the browser refresh button or F5 (no, clicking releases multiple times doesn't work). Notice the feed icon appear.
4. Go back to step 1.
5. Refresh the browser again.
6. Feed icon disappears again!

Just wanted to let you know.

**Comment by aureliendavid** [comment]
Hello, 

Thanks for the report. 

We have the same problem with youtube. 

See my answer here: https://github.com/aureliendavid/rsspreview/issues/79#issuecomment-1606224648

Basically when pages aren't fully loaded by the browser but use some internal loading mechanism then the extension doesn't run and cannot detect feeds. You have to f5 to fully load the page and detect feeds. 

Here we have the added weirdness of github not advertising the tags feed on the tags page (!) but advertising both feeds on the release page only (!!) (you can check source of the pages and ctrl+f ".atom" to verify this for example). 

So this is known issue + weird website behavior and I can't really do anything about it. 

But thanks for reporting anyway.
