### ISSUE TITLE
Description xhtml

### ISSUE THREAD

**Issue by nanaya** [aureliendavid/rsspreview#9]
Feeds with xhtml description currently have all of its (x)html tags stripped.

Example: https://rsstweet.myconan.net/2791517370/edogawa_test

Reference: https://tools.ietf.org/html/rfc4287#section-4.1.3.3

**Comment by aureliendavid** [comment]
hi, thanks for the report

this should now work with v2.3.1+

reopen the issue if the problem persists, thanks

**Comment by nanaya** [comment]
Thanks, it almost works now. I commented in the commit. Changing it to use `querySelectorAll` is probably the simplest fix for it.

**Comment by aureliendavid** [comment]
hopefully it's better now

**Comment by nanaya** [comment]
Looks great, thanks :+1:
